name: Deploy to FTP Server

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy-job:
    
    runs-on: ubuntu-latest

    steps:
      
      - name: Check out code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
